/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lojaabel.Telas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import lojaabel.Cliente;

/**
 *
 * @author Tequerro
 */
public class Telass extends javax.swing.JFrame {

    /**
     * Creates new form Telass
     */
    public Telass() {
        initComponents();                
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtoncadastrar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();
        jButtoneditar = new javax.swing.JButton();
        jButtonpesquisar = new javax.swing.JButton();
        jLabelid_cliente = new javax.swing.JLabel();
        jLabelnome = new javax.swing.JLabel();
        jLabelmorada = new javax.swing.JLabel();
        jLabelidade = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldid_idade = new javax.swing.JTextField();
        jTextFieldmorada = new javax.swing.JTextField();
        jTextFieldid_cliente1 = new javax.swing.JTextField();
        jTextFieldnome2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtoncadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtoncadastrar.setText("Cadastrar");
        jButtoncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 130, 50));

        jButtonexcluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonexcluir.setText("Excluir");
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, 50));

        jButtoneditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtoneditar.setText("Editar");
        getContentPane().add(jButtoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 130, 50));

        jButtonpesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonpesquisar.setText("Pesquisar");
        getContentPane().add(jButtonpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 130, 50));

        jLabelid_cliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelid_cliente.setText("id_cliente");
        getContentPane().add(jLabelid_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, -1));

        jLabelnome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelnome.setText("Nome");
        getContentPane().add(jLabelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, 70, 40));

        jLabelmorada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelmorada.setText("Morada");
        getContentPane().add(jLabelmorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, 40));

        jLabelidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelidade.setText("Idade");
        getContentPane().add(jLabelidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("TB CLIENTE");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jTextFieldid_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldid_idadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldid_idade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, 30));

        jTextFieldmorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmoradaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldmorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 270, 40));

        jTextFieldid_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldid_cliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldid_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, 30));

        jTextFieldnome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnome2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, 40));

        setSize(new java.awt.Dimension(578, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncadastrarActionPerformed
        // TODO add your handling code here:
        Cliente  cliente =  new Cliente(Integer.parseInt(jTextFieldid_cliente1.getText()), jTextFieldnome2.getText(), jTextFieldmorada.getText(), Integer.parseInt(jTextFieldid_idade.getText()));
        cliente.cadastrar(cliente);
    }//GEN-LAST:event_jButtoncadastrarActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
       Cliente clientesalvar  = new Cliente(Integer.parseInt(jTextFieldid_cliente1.getText()));
       clientesalvar.excluir(clientesalvar);
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jTextFieldid_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldid_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldid_idadeActionPerformed

    private void jTextFieldmoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmoradaActionPerformed

    private void jTextFieldid_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldid_cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldid_cliente1ActionPerformed

    private void jTextFieldnome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncadastrar;
    private javax.swing.JButton jButtoneditar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JButton jButtonpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelid_cliente;
    private javax.swing.JLabel jLabelidade;
    private javax.swing.JLabel jLabelmorada;
    private javax.swing.JLabel jLabelnome;
    public static javax.swing.JTextField jTextFieldid_cliente1;
    private javax.swing.JTextField jTextFieldid_idade;
    private javax.swing.JTextField jTextFieldmorada;
    private javax.swing.JTextField jTextFieldnome2;
    // End of variables declaration//GEN-END:variables
}
